"""
Wrapper for Python's logging package to simplify integration with guestshell
running on platforms running Cisco IOS XE Software.

Overview:
  1. Define a new logging subclass that defines a new method, "notice," to
     enable all built-in log levels in the Cisco IOS XE syslog.

  2. Define a logging filter to prepend expected fields for each generated
     message, including mapping the Python log levels to Cisco IOS XE levels.

  3. Provide a wrapper method that can be invoked from the guestshell Python
     script, simplifying implementation and reducing duplication across
     projects.


Copyright (c) 2026 Cisco and/or its affiliates.

This software is licensed to you under the terms of the Cisco Sample
Code License, Version 1.1 (the "License"). You may obtain a copy of the
License at

               https://developer.cisco.com/docs/licenses

All use of the material herein must be in accordance with the terms of
the License. All rights not expressly granted by the License are
reserved. Unless required by applicable law or agreed to separately in
writing, software distributed under the License is distributed on an "AS
IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied.
"""

__copyright__ = "Copyright (c) 2026 Cisco and/or its affiliates."
__license__ = "Cisco Sample Code License, Version 1.1"
__author__ = "Palmer Sample <psample@cisco.com>"


import logging
from sys import stdout as sys_stdout

# IOS XE log level values
XE_CRITICAL = 2
XE_ERROR = 3
XE_WARNING = 4
XE_NOTICE = 5
XE_INFO = 6
XE_DEBUG = 7


# Define the "NOTICE" loglevel for logging so all IOS XE levels are available
#
# NOTE: IOS XE expects the NOTICE log level to be between INFO and WARNING.
#       Python's logging module logs all values _above_ the minimum defined
#       logging level, where IOS XE logs all levels _below_ the level.
#
CUSTOM_NOTICE = 25


# Map Python logging levels to XE equivalent. Used by the Formatter to prepend
# the proper logging level for the device syslog.
PYTHON_TO_IOS_LOGLEVEL = {
    logging.DEBUG: XE_DEBUG,
    logging.INFO: XE_INFO,
    CUSTOM_NOTICE: XE_NOTICE,
    logging.WARNING: XE_WARNING,
    logging.ERROR: XE_ERROR,
    logging.CRITICAL: XE_CRITICAL,
}


class GuestShellLogging(logging.getLoggerClass()):
    """
    Custom logging class to define missing log levels and add corresponding
    logging methods to simplify usage.
    """

    def __init__(self,
                 name: str,
                 level: int = logging.NOTSET):
        """
        Initialize the logger and add custom levels expected by Guestshell.

        :param name: Name of the logger to initialize.
        :param level: Minimum level of log messages to display.
        """
        super().__init__(name, level)
        logging.addLevelName(CUSTOM_NOTICE, "NOTICE")

    def notice(self, msg, *args, **kwargs):
        """
        Log 'msg % args' with severity 'NOTICE'.

        To pass exception information, use the keyword argument exc_info with
        a true value, e.g.

        logger.debug("Admin, we have a %s", "noticeable issue", exc_info=True)

        :param msg: Message to be logged
        :param args: Additional arguments supported by logging.log()
        :param kwargs: Additional keyword args supported by logging.log()
        :return: None
        """
        if self.isEnabledFor(CUSTOM_NOTICE):
            self._log(CUSTOM_NOTICE, msg, args, **kwargs)


# pylint: disable=too-few-public-methods
class GuestShellFilter(logging.Filter):
    """
    Custom filter to set a logging record attribute with the IOS XE logging
    level.
    """

    def filter(self,
               record: logging.LogRecord) -> bool:
        """
        When a new log message (record) is generated, set a custom attribute
        named 'xe_log_level' that can be used in a formatter to translate
        standard logging levels into the corresponding level in IOS XE.

        :param record: LogRecord generated by the logging instance
        :return: True
        """
        record.xe_log_level = PYTHON_TO_IOS_LOGLEVEL[record.levelno]
        return True


# pylint: disable=unused-argument, line-too-long
def configure_guestshell_logging(logger_name: str = None,
                                 log_level: int = logging.DEBUG,
                                 enable_stdout: bool = True,
                                 enable_trace: bool = True) -> logging.Logger:
    """
    Wrapper function to create a logging instance and configure it with
    necessary handlers and formatters to support Guestshell logging on
    Cisco IOS XE Software via standard Python logging calls.

    :param logger_name: Name of the logger. Default: "__main__"
    :param log_level: Minimum logging level (logging.DEBUG will catch all).
    :param enable_stdout: (Default: True) - also log to STDOUT
    :param enable_trace: Future use - not implemented at this time.
    :return: Configured instance of the Python logging facility.
    """

    # Logging should use a custom class for this instance.
    logging.setLoggerClass(GuestShellLogging)

    # Instantiate a logger and add a custom filter.
    gs_logger = logging.getLogger(logger_name)
    gs_logger.addFilter(GuestShellFilter())

    # Output message:
    # [a123b234,1,5]Example notice message
    #
    # Device console shows:
    # *Aug  3 19:18:20.226: %IM-5-IOX_INST_NOTICE: Chassis 1 R0/0: ioxman: IOX SERVICE guestshell LOG: Example notice message
    gs_formatter = logging.Formatter(
        fmt="[a123b234,1,%(xe_log_level)s]%(message)s"
    )

    # Aug 03 19:18:00: __main__: NOTICE: Example message
    stdout_formatter = logging.Formatter(
        fmt="%(asctime)s: %(name)s: %(levelname)s: %(message)s",
        datefmt="%b %d %H:%M:%S"
    )

    # pylint: disable=consider-using-with
    try:
        # Send log messages to /dev/ttyS2
        console_handler = logging.StreamHandler(
            open("/dev/ttyS2", mode="w", encoding="utf-8")
        )
        console_handler.setFormatter(gs_formatter)
        gs_logger.addHandler(console_handler)
    except PermissionError as err:
        raise RuntimeError(
            f"Unable to open logging handle '/dev/ttyS2':\n{err}",
        ) from err

    if enable_stdout:
        stdout_handler = logging.StreamHandler(sys_stdout)
        stdout_handler.setFormatter(stdout_formatter)
        gs_logger.addHandler(stdout_handler)

    gs_logger.setLevel(log_level)

    return gs_logger
